apiVersion: v1
kind: Service
metadata:
  name: subhamipl123-service
spec:
  selector:
    app: subhamipl123
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subhamipl123
spec:
  selector:
    matchLabels:
      app: subhamipl123
  replicas: 1
  template:
    metadata:
      labels:
        app: subhamipl123
    spec:
      containers:
      - name: subhamipl123
        image: flight-api
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
